// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Twirla.Infrastructure.Persistence;

#nullable disable

namespace Twirla.Infrastructure.Migrations
{
    [DbContext(typeof(TwirlaDbContext))]
    [Migration("20260603211236_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.AnalyticsEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CouponCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("coupon_code");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("event");

                    b.Property<string>("Mode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("mode");

                    b.Property<string>("SessionId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("shop_id");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp_utc");

                    b.Property<decimal?>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.Property<string>("VisitorId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("visitor_id");

                    b.HasKey("Id");

                    b.HasIndex("ShopId", "Event");

                    b.HasIndex("ShopId", "TimestampUtc");

                    b.ToTable("analytics_events", (string)null);
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.CouponEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("coupon_code");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("generated_at_utc");

                    b.Property<decimal?>("OrderValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("order_value");

                    b.Property<DateTimeOffset?>("RedeemedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("redeemed_at_utc");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("shop_id");

                    b.HasKey("Id");

                    b.HasIndex("ShopId", "CouponCode")
                        .IsUnique();

                    b.ToTable("coupons", (string)null);
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopBrandingEntity", b =>
                {
                    b.Property<string>("ShopId")
                        .HasColumnType("TEXT")
                        .HasColumnName("shop_id");

                    b.Property<string>("AccentColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundMode")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrandName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoBackgroundColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("primary_color");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("secondary_color");

                    b.Property<string>("SpotAccent")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotDeep")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotMuted")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotWash")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThemeAmbientMotion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThemeBackgroundPattern")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ThemeBorderRadius")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ThemeButtonRadius")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThemeFontFamily")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThemeParticlesAccentColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThemeParticlesColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThemeParticlesDensity")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ThemeParticlesEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThemeParticlesShape")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThemeSurfaceStyle")
                        .HasColumnType("TEXT");

                    b.HasKey("ShopId");

                    b.ToTable("shop_branding", (string)null);
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopCampaignEntity", b =>
                {
                    b.Property<string>("ShopId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AboutAboutUs")
                        .HasColumnType("TEXT");

                    b.Property<string>("AboutCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("AboutCountry")
                        .HasColumnType("TEXT");

                    b.Property<string>("AboutOwnerPhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("AboutPhysicalAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("AboutWhatWeSell")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccentColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnabledGameModesJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("enabled_game_modes_json");

                    b.Property<string>("ExperiencesSlug")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExperiencesUniqueId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeaturedGame")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeaturedSectionTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("FontPairId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GamesSectionTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroBackgroundImageOverlay")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroBackgroundImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroBackgroundPattern")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroBackgroundStyle")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroCtaLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroCtaUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroHeadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroTagline")
                        .HasColumnType("TEXT");

                    b.Property<string>("HowToOrderBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("HowToOrderHeading")
                        .HasColumnType("TEXT");

                    b.Property<string>("HowToOrderPrimaryCtaLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("HowToOrderPrimaryCtaUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("LayoutTemplate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParticlesAccentColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParticlesColor")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParticlesCount")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ParticlesDotSize")
                        .HasColumnType("REAL");

                    b.Property<bool?>("ParticlesEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParticlesLinkDistance")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ParticlesSpeed")
                        .HasColumnType("REAL");

                    b.Property<string>("SocialEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialInstagram")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialTiktok")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialWebsite")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialWhatsapp")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotAccent")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotDeep")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotMuted")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotWash")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("translations_json");

                    b.Property<string>("ValueBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueHeadline")
                        .HasColumnType("TEXT");

                    b.HasKey("ShopId");

                    b.ToTable("shop_campaign", (string)null);
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopCampaignFaqEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("shop_campaign_faq", (string)null);
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopCampaignProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CtaLabel")
                        .HasColumnType("TEXT");

                    b.Property<string>("CtaUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("shop_campaign_products", (string)null);
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopCampaignTestimonialEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("shop_campaign_testimonials", (string)null);
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopCampaignTrustBadgeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("shop_campaign_trust_badges", (string)null);
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopCountdownEntity", b =>
                {
                    b.Property<string>("ShopId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowCtaBeforeEnd")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("translations_json");

                    b.HasKey("ShopId");

                    b.ToTable("shop_countdown", (string)null);
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopCtaEntity", b =>
                {
                    b.Property<string>("ShopId")
                        .HasColumnType("TEXT")
                        .HasColumnName("shop_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ShopId");

                    b.ToTable("shop_cta", (string)null);
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopEntity", b =>
                {
                    b.Property<string>("ShopId")
                        .HasColumnType("TEXT")
                        .HasColumnName("shop_id");

                    b.Property<string>("AdminToken")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("admin_token");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("Mode")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("mode");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("PlayCooldownHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(24)
                        .HasColumnName("play_cooldown_hours");

                    b.Property<string>("Slug")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("ShopId");

                    b.HasIndex("Slug");

                    b.ToTable("shops", (string)null);
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopMemoryEntity", b =>
                {
                    b.Property<string>("ShopId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxMistakes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PairCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PairLabelsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("pair_labels_json");

                    b.Property<string>("RevealSubtitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevealText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TimeLimitSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("translations_json");

                    b.HasKey("ShopId");

                    b.ToTable("shop_memory", (string)null);
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopRunnerGameEntity", b =>
                {
                    b.Property<string>("ShopId")
                        .HasColumnType("TEXT");

                    b.HasKey("ShopId");

                    b.ToTable("shop_runner_game", (string)null);
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopRunnerOutcomeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsNoWin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("shop_runner_outcomes", (string)null);
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopScratchEntity", b =>
                {
                    b.Property<string>("ShopId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OverlayColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OverlayText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RevealSubtitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevealText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("translations_json");

                    b.HasKey("ShopId");

                    b.ToTable("shop_scratch", (string)null);
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopTapHeartsEntity", b =>
                {
                    b.Property<string>("ShopId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeartColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HeartsToTap")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RevealSubtitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevealText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("translations_json");

                    b.HasKey("ShopId");

                    b.ToTable("shop_tap_hearts", (string)null);
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopTapHeartsOutcomeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsNoWin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("shop_tap_hearts_outcomes", (string)null);
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopTextEntity", b =>
                {
                    b.Property<string>("ShopId")
                        .HasColumnType("TEXT")
                        .HasColumnName("shop_id");

                    b.Property<string>("CtaText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxDiscountPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultSubtitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("translations_json");

                    b.HasKey("ShopId");

                    b.ToTable("shop_text", (string)null);
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopWheelEntity", b =>
                {
                    b.Property<string>("ShopId")
                        .HasColumnType("TEXT")
                        .HasColumnName("shop_id");

                    b.Property<bool>("AllowRepeatSpins")
                        .HasColumnType("INTEGER");

                    b.HasKey("ShopId");

                    b.ToTable("shop_wheel", (string)null);
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopWheelPrizeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsWinning")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("translations_json");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("shop_wheel_prizes", (string)null);
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.AnalyticsEventEntity", b =>
                {
                    b.HasOne("Twirla.Infrastructure.Persistence.Entities.ShopEntity", "Shop")
                        .WithMany("AnalyticsEvents")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.CouponEntity", b =>
                {
                    b.HasOne("Twirla.Infrastructure.Persistence.Entities.ShopEntity", "Shop")
                        .WithMany("Coupons")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopBrandingEntity", b =>
                {
                    b.HasOne("Twirla.Infrastructure.Persistence.Entities.ShopEntity", "Shop")
                        .WithOne("Branding")
                        .HasForeignKey("Twirla.Infrastructure.Persistence.Entities.ShopBrandingEntity", "ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopCampaignEntity", b =>
                {
                    b.HasOne("Twirla.Infrastructure.Persistence.Entities.ShopEntity", "Shop")
                        .WithOne("Campaign")
                        .HasForeignKey("Twirla.Infrastructure.Persistence.Entities.ShopCampaignEntity", "ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopCampaignFaqEntity", b =>
                {
                    b.HasOne("Twirla.Infrastructure.Persistence.Entities.ShopCampaignEntity", "Campaign")
                        .WithMany("Faq")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopCampaignProductEntity", b =>
                {
                    b.HasOne("Twirla.Infrastructure.Persistence.Entities.ShopCampaignEntity", "Campaign")
                        .WithMany("FeaturedProducts")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopCampaignTestimonialEntity", b =>
                {
                    b.HasOne("Twirla.Infrastructure.Persistence.Entities.ShopCampaignEntity", "Campaign")
                        .WithMany("Testimonials")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopCampaignTrustBadgeEntity", b =>
                {
                    b.HasOne("Twirla.Infrastructure.Persistence.Entities.ShopCampaignEntity", "Campaign")
                        .WithMany("TrustBadges")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopCountdownEntity", b =>
                {
                    b.HasOne("Twirla.Infrastructure.Persistence.Entities.ShopEntity", "Shop")
                        .WithOne("Countdown")
                        .HasForeignKey("Twirla.Infrastructure.Persistence.Entities.ShopCountdownEntity", "ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopCtaEntity", b =>
                {
                    b.HasOne("Twirla.Infrastructure.Persistence.Entities.ShopEntity", "Shop")
                        .WithOne("Cta")
                        .HasForeignKey("Twirla.Infrastructure.Persistence.Entities.ShopCtaEntity", "ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopMemoryEntity", b =>
                {
                    b.HasOne("Twirla.Infrastructure.Persistence.Entities.ShopEntity", "Shop")
                        .WithOne("Memory")
                        .HasForeignKey("Twirla.Infrastructure.Persistence.Entities.ShopMemoryEntity", "ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopRunnerGameEntity", b =>
                {
                    b.HasOne("Twirla.Infrastructure.Persistence.Entities.ShopEntity", "Shop")
                        .WithOne("RunnerGame")
                        .HasForeignKey("Twirla.Infrastructure.Persistence.Entities.ShopRunnerGameEntity", "ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopRunnerOutcomeEntity", b =>
                {
                    b.HasOne("Twirla.Infrastructure.Persistence.Entities.ShopRunnerGameEntity", "RunnerGame")
                        .WithMany("Outcomes")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RunnerGame");
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopScratchEntity", b =>
                {
                    b.HasOne("Twirla.Infrastructure.Persistence.Entities.ShopEntity", "Shop")
                        .WithOne("Scratch")
                        .HasForeignKey("Twirla.Infrastructure.Persistence.Entities.ShopScratchEntity", "ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopTapHeartsEntity", b =>
                {
                    b.HasOne("Twirla.Infrastructure.Persistence.Entities.ShopEntity", "Shop")
                        .WithOne("TapHearts")
                        .HasForeignKey("Twirla.Infrastructure.Persistence.Entities.ShopTapHeartsEntity", "ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopTapHeartsOutcomeEntity", b =>
                {
                    b.HasOne("Twirla.Infrastructure.Persistence.Entities.ShopTapHeartsEntity", "TapHearts")
                        .WithMany("Outcomes")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TapHearts");
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopTextEntity", b =>
                {
                    b.HasOne("Twirla.Infrastructure.Persistence.Entities.ShopEntity", "Shop")
                        .WithOne("Text")
                        .HasForeignKey("Twirla.Infrastructure.Persistence.Entities.ShopTextEntity", "ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopWheelEntity", b =>
                {
                    b.HasOne("Twirla.Infrastructure.Persistence.Entities.ShopEntity", "Shop")
                        .WithOne("Wheel")
                        .HasForeignKey("Twirla.Infrastructure.Persistence.Entities.ShopWheelEntity", "ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopWheelPrizeEntity", b =>
                {
                    b.HasOne("Twirla.Infrastructure.Persistence.Entities.ShopWheelEntity", "Wheel")
                        .WithMany("Prizes")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wheel");
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopCampaignEntity", b =>
                {
                    b.Navigation("Faq");

                    b.Navigation("FeaturedProducts");

                    b.Navigation("Testimonials");

                    b.Navigation("TrustBadges");
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopEntity", b =>
                {
                    b.Navigation("AnalyticsEvents");

                    b.Navigation("Branding");

                    b.Navigation("Campaign");

                    b.Navigation("Countdown");

                    b.Navigation("Coupons");

                    b.Navigation("Cta");

                    b.Navigation("Memory");

                    b.Navigation("RunnerGame");

                    b.Navigation("Scratch");

                    b.Navigation("TapHearts");

                    b.Navigation("Text");

                    b.Navigation("Wheel");
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopRunnerGameEntity", b =>
                {
                    b.Navigation("Outcomes");
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopTapHeartsEntity", b =>
                {
                    b.Navigation("Outcomes");
                });

            modelBuilder.Entity("Twirla.Infrastructure.Persistence.Entities.ShopWheelEntity", b =>
                {
                    b.Navigation("Prizes");
                });
#pragma warning restore 612, 618
        }
    }
}
